version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
      
  pre_build:
    commands:
      - echo Install dependencies
      - npm install

  build:
    commands:
      - echo Building for production
      - rm -rf node_modules
      - npm install --production

artifacts:
  files:
    - "**/*"
  name: Calculator-$(date +%Y-%m-%d) 
